# Generated by Django 3.2.8 on 2021-11-30 05:28

from django.db import migrations, models
import django.db.models.deletion
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home Page', 'verbose_name_plural': 'Home Pages'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_sub_tittle',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_tittle',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add title here', required=True)), ('text', wagtail.core.blocks.CharBlock(help_text='Add title here', required=True))])), ('Rich_text_editor', streams.blocks.Rich_Text_Block()), ('Info_block', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('title', wagtail.core.blocks.CharBlock(help_text='Add title here', required=True)), ('text', wagtail.core.blocks.CharBlock(help_text='Add title here', required=True)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_url', wagtail.core.blocks.URLBlock(required=False)), ('button_text', wagtail.core.blocks.CharBlock(default='Learn More', max_length=40, required=True))])), ('Cardblock', wagtail.core.blocks.StructBlock([('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(max_length=40, required=True)), ('button_text', wagtail.core.blocks.CharBlock(help_text='Enter button text here', required=False)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_url', wagtail.core.blocks.URLBlock(help_text='If the button page above is selected, that will be used first.', required=False))])))])), ('About_block', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='Best size 500 x 470 pixels ', required=False)), ('video', wagtail.core.blocks.URLBlock(help_text='Enter youtube video link here ', required=False)), ('title1_small', wagtail.core.blocks.CharBlock(help_text='Add title here', required=True)), ('title2_bold', wagtail.core.blocks.CharBlock(help_text='Add Big Bold title here', required=True)), ('text', wagtail.core.blocks.RichTextBlock(help_text='Add main para here', required=True)), ('icon1', wagtail.core.blocks.CharBlock(help_text='Add flaticon class here', required=False)), ('sub_title_1', wagtail.core.blocks.CharBlock(help_text='Add sub title 1 here', required=True)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_url', wagtail.core.blocks.URLBlock(required=False)), ('sub_title_text_1', wagtail.core.blocks.RichTextBlock(help_text='Add text under sub title 1 here', required=True)), ('icon2', wagtail.core.blocks.CharBlock(help_text='Add flaticon class here', required=False)), ('sub_title_2', wagtail.core.blocks.CharBlock(help_text='Add sub title 2 here', required=True)), ('button_page_1', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_url_1', wagtail.core.blocks.URLBlock(required=False)), ('sub_title_text_2', wagtail.core.blocks.RichTextBlock(help_text='Add text under sub title 2 here', required=True))])), ('About_block_2', wagtail.core.blocks.StructBlock([('title1_small', wagtail.core.blocks.CharBlock(help_text='Add title here', required=True)), ('title2_bold', wagtail.core.blocks.CharBlock(help_text='Add gig title text here', required=True)), ('text', wagtail.core.blocks.RichTextBlock(help_text='Add para here', required=True)), ('icon1', wagtail.core.blocks.CharBlock(help_text='Add flaticon class here', required=False)), ('sub_title_1', wagtail.core.blocks.CharBlock(help_text='Add title here', required=True)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_url', wagtail.core.blocks.URLBlock(required=False)), ('sub_title_text_1', wagtail.core.blocks.RichTextBlock(help_text='Add pare here', required=True)), ('icon2', wagtail.core.blocks.CharBlock(help_text='Add flaticon class here', required=False)), ('sub_title_2', wagtail.core.blocks.CharBlock(help_text='Add title here', required=True)), ('button_page_2', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_url_2', wagtail.core.blocks.URLBlock(required=False)), ('sub_title_text_2', wagtail.core.blocks.RichTextBlock(help_text='Add para here', required=True)), ('icon3', wagtail.core.blocks.CharBlock(help_text='Add flaticon class here', required=False)), ('sub_title_3', wagtail.core.blocks.CharBlock(help_text='Add title here', required=True)), ('button_page_3', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_url_3', wagtail.core.blocks.URLBlock(required=False)), ('sub_title_text_3', wagtail.core.blocks.RichTextBlock(help_text='Add para here', required=True)), ('icon4', wagtail.core.blocks.CharBlock(help_text='Add flaticon class here', required=False)), ('sub_title_4', wagtail.core.blocks.CharBlock(help_text='Add title here', required=True)), ('button_page_4', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_url_4', wagtail.core.blocks.URLBlock(required=False)), ('sub_title_text_4', wagtail.core.blocks.RichTextBlock(help_text='Add para here', required=True)), ('icon5', wagtail.core.blocks.CharBlock(help_text='Add flaticon class here', required=False)), ('imagebox_heading', wagtail.core.blocks.CharBlock(help_text='Add headign for box over image here', required=True)), ('imagebox_text', wagtail.core.blocks.CharBlock(help_text='Add text for box over image here', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Best size 460 x 455 pixels ', required=False))])), ('About_block_3', wagtail.core.blocks.StructBlock([('title1_small', wagtail.core.blocks.CharBlock(help_text='Add title here', required=True)), ('title2_bold', wagtail.core.blocks.CharBlock(help_text='Add gig title text here', required=True)), ('text', wagtail.core.blocks.RichTextBlock(help_text='Add para here', required=True)), ('sub_title_1', wagtail.core.blocks.CharBlock(help_text='Add title here', required=True)), ('sub_title_1_text', wagtail.core.blocks.RichTextBlock(help_text='Add pare here', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Best size 460 x 455 pixels ', required=False))])), ('About_block_4', wagtail.core.blocks.StructBlock([('title1_small', wagtail.core.blocks.CharBlock(help_text='Add title here', required=True)), ('title2_bold', wagtail.core.blocks.CharBlock(help_text='Add gig title text here', required=True)), ('text', wagtail.core.blocks.RichTextBlock(help_text='Add para here', required=True)), ('sub_title_1', wagtail.core.blocks.CharBlock(help_text='Add title here', required=True)), ('percent1', wagtail.core.blocks.RichTextBlock(help_text='Add % here', required=True)), ('sub_title_2', wagtail.core.blocks.CharBlock(help_text='Add title here', required=True)), ('percent2', wagtail.core.blocks.RichTextBlock(help_text='Add % here', required=True)), ('sub_title_3', wagtail.core.blocks.CharBlock(help_text='Add title here', required=True)), ('percent3', wagtail.core.blocks.RichTextBlock(help_text='Add % here', required=True)), ('sub_title_4', wagtail.core.blocks.CharBlock(help_text='Add title here', required=True)), ('percent4', wagtail.core.blocks.RichTextBlock(help_text='Add % here', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Best size 500 x 530 pixels ', required=False))])), ('Accordion_Block', wagtail.core.blocks.StructBlock([('Block_Title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True)), ('First_Section_Title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True)), ('First_Section_Content_Heading', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True)), ('First_Section_Content_Text', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True)), ('Sections', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('Section_ID', wagtail.core.blocks.CharBlock(help_text='Make sure you must enter a unique word or alphanumeric text as ID', max_length=40, required=True, unique=True)), ('Section_Title', wagtail.core.blocks.CharBlock(help_text='Enter Title for the sections text here', max_length=40, required=True)), ('Section_Content_Heading', wagtail.core.blocks.CharBlock(help_text='Enter heading for the sections text here', required=False)), ('Section_Content_Text', wagtail.core.blocks.CharBlock(help_text='Enter text for the sections here', required=False)), ('Button_Text', wagtail.core.blocks.CharBlock(help_text='Enter button text here, button will only appear if you either provide inner or external link', required=False)), ('Button_Page', wagtail.core.blocks.PageChooserBlock(required=False)), ('Button_Url', wagtail.core.blocks.URLBlock(help_text='If the button page above is selected, that will be used first.', required=False))])))])), ('Simple_Horizontal_Divider', wagtail.core.blocks.StructBlock([])), ('Tabs1Block', wagtail.core.blocks.StructBlock([('Block_Title', wagtail.core.blocks.CharBlock(help_text='Add section title here', required=False)), ('First_tab_Title', wagtail.core.blocks.CharBlock(help_text='Add Title for the first tab', required=True)), ('First_Section_Content_Heading', wagtail.core.blocks.CharBlock(help_text='Add Heading for the first tab', required=True)), ('First_Section_Content_Text', wagtail.core.blocks.CharBlock(help_text='Add Text for the first tab', required=True)), ('Button_Text', wagtail.core.blocks.CharBlock(help_text='Enter button text here, button will only appear if you either provide inner or external link', required=False)), ('Button_Page', wagtail.core.blocks.CharBlock(help_text='You can select a page to connect to the button', required=False)), ('Button_Url', wagtail.core.blocks.URLBlock(help_text='If the button page above is selected, that will be used first.', required=False)), ('tabs', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('Tab_ID', wagtail.core.blocks.CharBlock(help_text='Make sure you must enter a unique word or alphanumeric text as ID', max_length=40, required=True, unique=True)), ('Tab_Title', wagtail.core.blocks.CharBlock(help_text='Enter Title for the sections text here', max_length=40, required=True)), ('Section_Content_Heading', wagtail.core.blocks.CharBlock(help_text='Enter heading for the sections text here', required=False)), ('Section_Content_Text', wagtail.core.blocks.RichTextBlock(help_text='Enter text for the sections here', required=False)), ('Button_Text', wagtail.core.blocks.CharBlock(help_text='Enter button text here, button will only appear if you either provide inner or external link', required=False)), ('Button_Page', wagtail.core.blocks.PageChooserBlock(help_text='You can select a page to connect to the button', required=False)), ('Button_Url', wagtail.core.blocks.URLBlock(help_text='If the button page above is selected, that will be used first.', required=False))])))])), ('ImageSliderBlock', wagtail.core.blocks.StructBlock([('images', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text=' best size is 140 x 130 pixels', required=True)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_url', wagtail.core.blocks.URLBlock(help_text='If the button page above is selected, that will be used first.', required=False))])))])), ('info_block1', wagtail.core.blocks.StructBlock([('title1_small', wagtail.core.blocks.CharBlock(help_text='Add title here', required=True)), ('title2_bold', wagtail.core.blocks.CharBlock(help_text='Add gig title text here', required=True)), ('paragraph', wagtail.core.blocks.RichTextBlock(help_text='Add paragraph here', required=True)), ('button_label', wagtail.core.blocks.CharBlock(help_text='Add button lable here', required=True)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_url', wagtail.core.blocks.URLBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Best size 570 x 350 pixels ', required=False))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='header_address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='logo_dark_bg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='logo_dark_bg_cta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='logo_white_bg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='logo_white_bg_cta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='support',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
