# Generated by Django 3.2.8 on 2021-11-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediasettings',
            name='googleplus',
            field=models.URLField(blank=True, help_text='Youtube channel URL', null=True),
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='linkedin',
            field=models.URLField(blank=True, help_text='Youtube channel URL', null=True),
        ),
    ]
